apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-api
  namespace: kashtanka
  labels:
    app: kafka-rest-api
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: web
  selector:
    app: kafka-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest-api
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: kafka-rest-api
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka-rest-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kafka-rest-api
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rest-api
        image: lostpetinitiative/kafka-rest-api:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicate-image-remover
  namespace: kashtanka
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: duplicate-image-remover
  template:
    metadata:
      labels:
        app: duplicate-image-remover
    spec:
      containers:
      - name: worker
        image: lostpetinitiative/duplicate-image-remover:1.4.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        - name: INPUT_QUEUE
          value: kashtanka_crawled_pet_cards
        - name: OUTPUT_QUEUE
          value: kashtanka_distinct_photos_pet_cards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-image-detector
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: pet-image-detector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pet-image-detector
    spec:
      containers:
      - name: worker
        image: lostpetinitiative/pet-image-extractor-yolo4:1.1.1
        resources:
          requests:
            memory: "2048Mi"
            cpu: "25m"
          limits:
            #memory: "3072Mi"
            memory: "2048Mi"
            cpu: "2"
        # ports:
        # - containerPort: <Port>
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        - name: INPUT_QUEUE
          value: kashtanka_distinct_photos_pet_cards
        - name: OUTPUT_QUEUE
          value: kashtanka_detected_pets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processed-cards-persister
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: processed-cards-persister
  template:
    metadata:
      labels:
        app: processed-cards-persister
    spec:
      containers:
      - name: worker
        image: lostpetinitiative/processed-cards-persister:1.1.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        - name: INPUT_QUEUE
          value: kashtanka_cards_with_features
        - name: CARD_STORAGE_REST_API_URL
          value: http://cassandra-rest-api
        - name: CARD_INDEX_REST_API_URL
          value: http://solr.default/solr/kashtankacards/update/json/docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extractor-dogs
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: feature-extractor-dogs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feature-extractor-dogs
    spec:
      containers:
      - name: worker
        image: lostpetinitiative/pet-feature-extractor:1.1.1
        resources:
          requests:
            memory: "2048Mi"
            cpu: "25m"
          limits:
            #memory: "3072Mi"
            memory: "2048Mi"
            cpu: "1"
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        - name: INPUT_QUEUE
          value: kashtanka_detected_pets
        - name: OUTPUT_QUEUE
          value: kashtanka_cards_with_features
        - name: ANIMAL_TYPE
          value: dog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extractor-cats
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: feature-extractor-cats
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feature-extractor-cats
    spec:
      containers:
      - name: worker
        image: lostpetinitiative/pet-feature-extractor:1.1.1
        resources:
          requests:
            memory: "2048Mi"
            cpu: "25m"
          limits:
            #memory: "3072Mi"
            memory: "2048Mi"
            cpu: "1"
        env:
        - name: KAFKA_URL
          value: kafka-cluster.default:9092
        - name: INPUT_QUEUE
          value: kashtanka_detected_pets
        - name: OUTPUT_QUEUE
          value: kashtanka_cards_with_features
        - name: ANIMAL_TYPE
          value: cat
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-rest-api
  namespace: kashtanka
  labels:
    app: cassandra-rest-api
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: web
  selector:
    app: cassandra-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-rest-api
  namespace: kashtanka
spec:
  selector:
    matchLabels:
      app: cassandra-rest-api
  replicas: 2
  template:
    metadata:
      labels:
        app: cassandra-rest-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - cassandra-rest-api
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rest-api
        image: lostpetinitiative/cassandra-rest-api:1.1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: CASSANDRA_ADDRS
          value: cass-hs.default.svc.cluster.local
        - name: KEYSPACE
          value: kashtanka
        ports:
        - containerPort: 5000
