apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
spec:
  selector:
    app: solr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8983
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: solr-pdb
spec:
  selector:
    matchLabels:
      app: solr
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  selector:
    matchLabels:
      app: solr
  serviceName: solr
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: solr
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: "app"
      #               operator: In
      #               values:
      #               - zk
      #         topologyKey: "kubernetes.io/hostname"
      containers:
      - name: solr
        imagePullPolicy: Always
        image: "solr:8"
        resources:
          requests:
            memory: 1Gi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "1"
        env:
            - name: ZK_HOST
              value: zk-0.zk-hs,zk-1.zk-hs,zk-2.zk-hs # solr monitors ZK cluster itself. this, not zk-cs
            - name: SOLR_HEAP
              value: 1024m
            - name: SOLR_JAVA_MEM
              value: -Xms512m -Xmx1024m
        ports:
        - containerPort: 8983
        volumeMounts:
        - name: datadir
          mountPath: //var/solr      
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi